on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
jobs:
 - name: Use joshstrange/setup-quasar
   uses: joshstrange/setup-quasar@v1
   with:
     cordova-version: 9

- name: Build
  run: |
    quasar build -m cordova -T ios     

