on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3

        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --token ${{ secrets.NPM_TOKEN }}

